### PR TITLE
Filter by category

### LINKED ISSUE #1: Bounties Explorer: Filter by Category

### PR DESCRIPTION
**Pull request by rymksotnini**
Closes #1

### CODE REVIEW

**Comment by mehranhydary** [comment]
@rymksotnini - most of it looks good. Seems like your .gitignore file isn't working since the .idea stuff is still being pulled in

**Comment by rymksotnini** [comment]
> @rymksotnini - most of it looks good. Seems like your .gitignore file isn't working since the .idea stuff is still being pulled in

Yep! The problem was in the first push before adding it to the gitignore. Do you want me to delete those manually from github?

**Comment by mehranhydary** [comment]
@rymksotnini - hi Rym! let me know when you update the PR so that it removes the files you area trying to ignore. Thank you

**Comment by rymksotnini** [comment]
@mehranhydary - Hello Mehran! I just deleted those files and updated the PR

**Pull request merged**
